/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    Relp: typeof import('./src/components/Relp.vue')['default']
    TinyButtonGroup: typeof import('@opentiny/vue')['ButtonGroup']
    TinyOption: typeof import('@opentiny/vue')['Option']
    TinySelect: typeof import('@opentiny/vue')['Select']
    TinySwitch: typeof import('@opentiny/vue')['Switch']
  }
}
